### PR TITLE
Add pip installation command to README

### PR DESCRIPTION
**Pull request by akki**
I found the project interesting & useful. And I believe it would be helpful to have the pip package name in the readme.

### CODE REVIEW

**Comment by haaksmash** [comment]
glad you found it useful! good point about the package name, since it doesn't match the repo title.

It looks like something has failed in the build for python 3---do you have time to look into that? it's almost certainly not related to your README change, but I think it's wise to not accept red commits.

**Comment by akki** [comment]
I did look into that yesterday but I found, as you said, it is not related to changes in the README.

I tried a quick fix here - https://github.com/haaksmash/pyutils/pull/18 but seems like it needs deeper investigation, into which I won't be able to invest my time.


FWIW, I believe it is not wise to mix 2 unrelated issues i.e. hindering a fix in the README because the repository's CI is broken (especially when the CI doesn't check the README at all). It might be better to fix the CI as a part of another issue - just my opinion. :)

**Comment by haaksmash** [comment]
100% agreed that we shouldn't mix unrelated issues---fixing the CI should definitely be its own pull request :) I'll take a look (thanks for the starting point in #18 !) and see what I can figure out!

**Comment by haaksmash** [comment]
@akki I think I've fixed the build with #19; mind rebasing/merging to get a green commit?

**Comment by akki** [comment]
Still fails. Seems like some network issue on the server.

**Comment by akki** [comment]
@haaksmash Passes now.

**Pull request merged**
